#:schema https://developers.openai.com/codex/config-schema.json

approval_policy = "untrusted"
file_opener = "none"
sandbox_mode = "workspace-write"

[features]
apps = false

[mcp_servers.github]
bearer_token_env_var = "GITHUB_TOKEN"
url = "https://api.githubcopilot.com/mcp/readonly"

[projects."/home/codex/projects"]
trust_level = "trusted"

[sandbox_workspace_write]
network_access = true

[shell_environment_policy]
ignore_default_excludes = true
include_only = ["HOME", "PATH", "SHELL", "TERM", "TMPDIR", "USER"]
inherit = "none"
