apiVersion: v1
kind: Pod
metadata:
  name: codex
spec:
  containers:
    - image: localhost/codex:0.1.0
      name: codex
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 1Gi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /home/codex/.codex
          name: codex
        - mountPath: /home/codex/projects
          name: projects
        - mountPath: /home/codex/.secrets
          name: secrets
  restartPolicy: Never
  volumes:
    - hostPath:
        path: ${ROOT_DIR}/volumes/codex
        type: DirectoryOrCreate
      name: codex
    - hostPath:
        path: ${ROOT_DIR}/volumes/projects
        type: DirectoryOrCreate
      name: projects
    - hostPath:
        path: ${ROOT_DIR}/volumes/secrets
        type: DirectoryOrCreate
      name: secrets
